name: yolo-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.4
  - pandas=2.0.3
  - pip:
    - streamlit==1.29.0
    - ultralytics==8.0.196
    - opencv-python-headless==4.8.0.76
    - google-cloud-storage==2.13.0
    - torch==2.0.1
    - torchvision==0.15.2
    - watchdog==3.0.0 