[server]
fileWatcherType = "none"

[runner]
# メモリ使用量を減らすための設定
fastReruns = true

[browser]
# 自動でブラウザを開かない設定（オプション）
gatherUsageStats = false 

[env]
# NumPy互換性問題を回避するための設定
KMP_DUPLICATE_LIB_OK = "TRUE"
# GPUを使用しない設定
CUDA_VISIBLE_DEVICES = "" 